name: dart_telegram_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  teledart: ^0.6.1
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.1
  http: ^1.4.0
  # dart_telegram_bot: ^0.5.0  # Telegram bot uchun kerakli paket

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0